import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/navbar"
import Footer from "@/components/footer"
import Procedimentos from "@/components/procedimentos"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" data-theme="light" className="min-h-screen">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Procedimentos />
        <button className="fixed -bottom-1 left-1/2 transform -translate-x-1/2 bg-black text-white p-4 w-full sm:w-36 font-semibold text-xl z-50">
          BOOK
        </button>
        <Footer />
      </body>
    </html>
  )
}
